### ISSUE TITLE
弱问下实验中字向量和词向量的初始化都是怎么做的？

### ISSUE THREAD

**Issue by guotong1988** [ShannonAI/Is-Word-Segmentation-Necessary#1]
多谢！

**Comment by stepperL** [comment]
您好～中文字向量和词向量都是随机初始化的，相比于有预训练的字或者词向量，随机初始化的向量维度要小一些。我们同时也做了使用预训练的字／词向量作为模型输入的实验，发现最后模型的效果收到预训练向量质量的影响。您可以参考BQ数据集，之前有一些工作是基于预训练的词向量，可以作为参考。谢谢～
